# Site settings
title: Codesleuth
name: Codesleuth
email: david.p.wood@gmail.com
description: Dave Emitter
tagline: Read my stuff
baseurl: ""
url: "http://www.codesleuth.co.uk"
permalink: /:year/:month/:title
paginate: 5
paginate_path: "/page/:num"
timezone: Europe/London

# Custom settings
blog_url: "https://medium.com/@Codesleuth"
twitter_username: codesleuth
github_username: codesleuth
stackoverflow_userid: 209668
stackoverflow_username: codesleuth

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: <!--more-->

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      published: false
      author: "David Wood"
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: "David Wood"
      layout: "post"
  -
    scope:
      path: "notes"
      type: "pages"
    values:
      layout: "note"

gems:
  - jekyll-sitemap
  - jekyll-feed
